### ISSUE TITLE
Device id is missing

### ISSUE THREAD

**Issue by otherprod** [herverenault/Self-Hosted-GPS-Tracker#10]
Salut et merci pour cette application simple, ce n'est pas un bug en soi mais il aurait été au top d'avoir l'identifiant du téléphone (deviceid) qui envoie la requête de manière à pouvoir les identifier :) côté serveur, merci

**Comment by herverenault** [comment]
Salut

Content que ça t'ait plu. Tu peux ajouter les paramètres que tu veux dans l'URL, par exemple http://monserveur/?deviceid=toto ;-)

**Comment by otherprod** [comment]
vraiment je suis bête :)

**Comment by otherprod** [comment]
merci

**Comment by herverenault** [comment]
Non tu n'es pas bête, ce n'est pas évident ! Disons que c'est "caché dans le code source" :-) 

Bonne soirée
