### ISSUE TITLE
i wish i can see the line when we move

### ISSUE THREAD

**Issue by muafakul** [herverenault/Self-Hosted-GPS-Tracker#12]
Something like draw the canvas automatic when we move

**Comment by herverenault** [comment]
There are several ways to do that:
You can do it in JavaScript, as long as you keep your browser window opened.
You can do it if you record the position in a database, and then select a range of data (for example, last 10 minutes or from latest "start" request)
But this is out of this project's scope.

**Comment by virtadpt** [comment]
It's pretty straightforward (for "I know what I'm doing" values of straightforwared) to write a webapp that takes the coordinates from this project and generates a map that updates in realtime.
