### ISSUE TITLE
Additional parameters on HTTP(S) request

### ISSUE THREAD

**Issue by keynlotepan** [herverenault/Self-Hosted-GPS-Tracker#16]
Hi all,

I have been using Osmand as tracking app until now. Recently I found your app which is very convenient as a standalone app for exactly this functionality and it additionally offers HTTPS support.
But to be able to use it for my (private) web application (which stores tracks in a MySQL database and displays tracks on Google Maps) I am missing timestamp parameter as supplied by Osmand.

All parameters of Osmand are listed on http://sourceforge.net/p/geo5/wiki/Home/#osmand-as-sender 

At least the timestamp parameter {2} would be very useful because on a mobile network there might be a considerable delay between capture and request completion.

Thanks a lot

**Comment by herverenault** [comment]
Hi,

This feature will be in next version coming out pretty soon!

**Comment by herverenault** [comment]
Added timestamp option in version 1.3.
