### ISSUE TITLE
Provide capture intervals < 30s 

### ISSUE THREAD

**Issue by keynlotepan** [herverenault/Self-Hosted-GPS-Tracker#17]
I am using GPS tracker for the same purpose tracking my position as you describe it in README.md during jogging in isolated locations. After a health incident some years ago I feel more secure to know that I could be rescued from somewhere in wood in such a situation. But I also use the gathered data to account running distances. For this purpose 30s interval is a little to infrequent to obtain accurate results.
I fear the reason for your decision to limit interval to 30s deals with HTTP communication timeouts and cannot be reduced without structural change. So I would encourage to implement a queue between position capture and network transmit. This could also bridge time gaps in cases of temporary mobile network signal loss situations.
I am sorry not to be very suitable to contribute with some code examples to implement such a change since my native languages are C++, Perl, Javascript and Python whereas my Java experience is very poor. But I could make an attempt if you support code contribution and agree my propsal.

**Comment by herverenault** [comment]
Thank you for offering your help, I appreciate.

I'm about to release a version in which you can go down to a 10 seconds interval. It may drain your battery pretty fast, though, so I think I will have to display some warning.

I don't think a queue is useful. Imagine you're stuck somewhere for, say, 1 hour, out of network coverage. Then, hopefully, you get some network access for a few seconds. What's important, then, is to manage to send your current location. You won't care about previous locations in this case. If you're really interested in recording GPX tracks, there are already excellent apps such as OsmAnd or Open GPS tracker. I personally use both my app and OsmAnd when I want to record my track.

**Comment by herverenault** [comment]
Capture interval down to 10 seconds will be released in version 1.4 coming up soon.

**Comment by vapor99** [comment]
Cool!  I'll try that out too for testing

**Comment by herverenault** [comment]
Eventually, a 10 seconds interval is no battery killer.

**Comment by keynlotepan** [comment]
Battery drain is an important aspect - the user should be informed about this fact when choosing a high capturing rate - but limitations should be avoided because it also reduces the range of possible use cases.

As described I use online tracking applications (Self-Hosted-GPS-Tracker and Osmand) for outdoor activities and I use the location data not only for displaying it (for example too get together again with my wife after different activities in a foreign city) but I also collect the same data in a database to display the covered route on a map and giving the total distance. On Osmand I configured an interval of 5s which takes about 15% battery capacity per hour of operation on my Samsung S3. Thats not really an excessive drain because not all activities take many hours. But for accuracy point of view this interval is required since distance travelled on a bike is not small (30m within a 5s interval). Another reason for choosing a high rate is the accuracy of GPS capturing. I have the impression that on choosing a 5s interval Osmand is more accurate in detecting location compared to a 30s interval. The Reason might be that the GSP receiver does not fall asleep and therefore must not be resyncd when using fast intervals.

Summarized I am convinced that it makes sense to design Self-Hosted-GPS-Tracker to be an application that is suitable to inform about your current position AND to do that in a way that those data can simultaneously be used for tracking capturing. It is exactly the same captured data that is to be evaluated in those both way.

I understand your arguments that introducing only a queue is has drawbacks in environments with poor mobile signal coverage. This could be solved by using a fifo stack instead of a queue. And since timestamp is transmitted now (thanks for that feature, I just downloaded 1.3 from f-droid - thanks also, for publishing on that great platform, because I run my mobile without a sniffing Google account) the receiving application can store the timestamp and distinguish between latest and subsequently sent buffer data.

In later versions the buffer can also be used for a reduction of transmission actions. Using different intervals for capture and send, it would be possible to send multiple locations within a single HTTP POST request which is capable to transport arbitrary amount of data.

Sorry for my late and overtexting reply. In contrast weekdays I have time now since weather is not too fine today.

**Comment by herverenault** [comment]
You mean a LIFO but I get the idea.

I'm using a 5 second interval on a local branch. I'll take a look at how it works, particularly in poor network condition, and then I'll start implementing the feature.

**Comment by keynlotepan** [comment]
I had a LIFO in mind but wrote FIFO what makes no sense since the latter would be a queue again. Sorry for confusing, but good that you got the idea.
Implementing a particular class for the FIFO entries would be helpful for encapsulation - for example for lifetime operations (drop FIFO bottom entries that exceeded configured lifetime). But probably you did have the same idea, too.
