### ISSUE TITLE
Add support for self-signed HTTPS certificates

### ISSUE THREAD

**Issue by kabo** [herverenault/Self-Hosted-GPS-Tracker#21]
It would be great if, when connecting to a server with a self-signed HTTPS-certificate, there would be a dialog asking the user to confirm the certificate. Like when you browse to a website with a self-signed certificate using Firefox. Now it just fails saying there was an error with the https connection.

**Comment by herverenault** [comment]
It's a good idea. I'll take a look at this.

**Comment by ThomasRgbg** [comment]
Please don't take this as advertising.... :) 
Just as a remark, let's encrypt (https://letsencrypt.org) is now available. So in case you have a DNS name for your server, no need for self-signed certificates anymore.

**Comment by herverenault** [comment]
@ThomasRgbg True :) but it's more complex than a self-signed certificate.
I hope I can find some time some day for working on this issue...

**Comment by herverenault** [comment]
As mentioned by @ThomasRgbg, Let's Encrypt makes this issue pretty much outdated.
