### ISSUE TITLE
GPS buffer

### ISSUE THREAD

**Issue by stormbyte** [herverenault/Self-Hosted-GPS-Tracker#22]
I would love to use this app to map out walking routes. 
But data transmission is not always possible when in the woods. 
It would be nice if the app could buffer these locations and send them to the recieving server when data transmission  is availible. Timestamp would be nessesary to get the correct chronological order.
But the app would need to be able to start without data transmission.

**Comment by herverenault** [comment]
This is exactly what Open GPS Tracker does. It does it well and it's open source. I recommend using this app. https://code.google.com/p/open-gpstracker/

**Comment by luchope** [comment]
Hi herverenault, really appretiate your app. Would be nice a temp buffer that stores data or send while internet is available.

Excuses for repeating the peticion  :)
