### ISSUE TITLE
Never post data?

### ISSUE THREAD

**Issue by ToeJet** [herverenault/Self-Hosted-GPS-Tracker#23]
I have 2 different devices that after launching the application, configuring the url, then hitting the tracker button never check in.  Both stay at 'Waiting for GPS data'.   I confirm with other apps (Google maps, osmand) that location is known on the device. 

Server logs indicate initial connection when client is started, but never an update with location.
[21/Oct/2015:08:25:53 -0400] 209.194.228.130 TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256 "GET /Self-Hosted-GPS-Tracker/server-side/gps.php?tracker=start HTTP/1.1" 2

device1 is a Nexus 9 with Android 6.0 going against a server with https and a self signed certificate. 
device 2 is a Droid Maxx with Android 4.4 going against a server with http

Tried swapping urls between devices with no success.  
browsing on either server,  
https://{REDACTED}/Self-Hosted-GPS-Tracker/server-side/gps.php?lat=35.95&lon=-78.55
or 
http://{REDACTED}/Self-Hosted-GPS-Tracker/server-side/gps.php?lat=35.95&lon=-78.55
will generate a gps-position.txt file.  

Client is the latest 1.7 installed from F-Droid. 
Server is latest examples from git-hub. 

Is there logging or some way to force a manual update from the client?

**Comment by herverenault** [comment]
That's weird. Updates are triggered by the gps receiver. So, if it says "waiting..." it means that the app doesn't receive any update. And there's no way of logging or forcing a manual update in this version. I'll think about it and get back to you later.

**Comment by Black-Fry** [comment]
Hey hey, great project! I am facing exactly the same problem like ToeJet does. App-Version (V 1.7, F-Droid) and server-side-code are equal. Only path of "gps-location.txt" has been changed. Android device is a HTC One mini, OS is a non-rooted Android 4.4.2 (4.14.401.2) dealing with HTC Sense Version 6.0 (API 6.20)

**Comment by herverenault** [comment]
So far, the only thing I can tell is that you both use the F-Droid binary. So, can you please try with the Google Play binary? I'm using this one and it works for me. Just to be sure nothing went wrong in the F-Droid compilation...

**Comment by Black-Fry** [comment]
I have been trying both app-versions now - google play store and f-droid. as I am sitting in a room without GPS-availability, I did not recognize, that geo-recognition only via network isn't running properly. placing the smartphone near to the window made me recognize, that gps returned a valid position. can you reproduce the problem by disabling gps?

**Comment by herverenault** [comment]
If you disable GPS, it won't work. This app is not made to use geo-recognition via network. You should see a message "GPS disabled" in red above the "Tracker" button.

**Comment by Black-Fry** [comment]
they're both enabled. but due toe a lack of gps-availability within the building, i cannot receive a valid position - gps-satelite is blinking for hours. i guess, geo-location should be possible using network-connection (dont care about less accuracy) as well. anyway, within the building i do not receive a valid position

**Comment by herverenault** [comment]
Oh, that's a good point! Thank you for clarifying. This is ambiguous, indeed. I need to reword that.

**Comment by herverenault** [comment]
Even better: I would like to add geo-location through the mobile network. I need to find some time to look into it... or ask contributors ;)

**Comment by ToeJet** [comment]
In my test,  it is a real gps signal.  Google location services are turned off.  Location mode is Device Only.  App source did not make a difference.
