### ISSUE TITLE
When clicked the tracker button pinging successfully when turnoff tracker send the request  ?  

### ISSUE THREAD

**Issue by Ranjithsolthi** [herverenault/Self-Hosted-GPS-Tracker#24]
How to send the request tracker is on off status to my server ?
if tracker  is active when status=1
if tracker  is inactive when status=2 how can i identify? in gps.php

**Comment by herverenault** [comment]
App sends tracker=start or tracker=stop when you hit the tracker button. Does it answer your question?

**Comment by Ranjithsolthi** [comment]
Thank you herverenault

**Comment by Ranjithsolthi** [comment]
if mobile /wifi network not available how can i set the lat,log values to zero on my server?
