### ISSUE TITLE
if mobile /wifi network not available how can i set the lat,log values to zero on my server?

### ISSUE THREAD

**Issue by Ranjithsolthi** [herverenault/Self-Hosted-GPS-Tracker#25]
if mobile /wifi network not available how can i set the lat,log values to zero on my server?

**Comment by herverenault** [comment]
If the app can't connect, there's nothing you can do... Except, maybe, after some time you can consider location as expired on the server?

**Comment by Ranjithsolthi** [comment]
yes how can i do that one in geo.php

**Comment by herverenault** [comment]
This is relevant to how you process information on your server, not to the app itself. Closing.
