### ISSUE TITLE
Serverside in python

### ISSUE THREAD

**Issue by ThomasRgbg** [herverenault/Self-Hosted-GPS-Tracker#36]
Hi, 

not finished and not so nice regex checking yet. But I wanted to run the serverside data-receiver (gps.php) on a lighter http server not needing php, apache etc. So I did a little implementation in python:

httpserver.py  (just copy/paste from docs.python.org)
```
#!/usr/bin/env python

import BaseHTTPServer
import CGIHTTPServer
import cgitb; cgitb.enable()  ## This line enables CGI error reporting

server = BaseHTTPServer.HTTPServer
handler = CGIHTTPServer.CGIHTTPRequestHandler
server_address = ("", 80)
handler.cgi_directories = ["/cgi-bin"]

httpd = server(server_address, handler)
httpd.serve_forever()
```

cgi-bin/gps.py  (make it chmod +x) 
```
#!/usr/bin/env python

import cgi

from datetime import datetime

print("Content type:text/html\r\n\r\n")
print("<html>")
print("<head>")
print("<title></title>")
print("</head>")
print("<body>")

form = cgi.FieldStorage()

if "lon" not in form or "lat" not in form:
    print("<h1> Error </h1>")
else:
    lon = form.getvalue('lon')
    lat = form.getvalue('lat')
    now = datetime.now()

    # debug
    # print("<p> long: {0}, lat: {1} </p>".format(lon,lat))

    f = open('/tmp/gps-position.txt','w')
    f.write('{0}_{1}_{2}'.format(now.__str__(),lat,lon) )
    f.close()

    print("OK")

print("</body>")
print("</html>")
```
Anyone interested in this ? Then I could make it a bit more like the original.

**Comment by herverenault** [comment]
I'm interested. This would make the server-side more language-neutral.

**Comment by virtadpt** [comment]
@ThomasRgbg You might want to check this out, too: https://github.com/virtadpt/exocortex-halo/tree/master/exocortex_gps_mapper

**Comment by ThomasRgbg** [comment]
Good to know... then lets keep my example here as simple as it is, yours looks hard to compete. 

By the way, just found https://github.com/mendhak/gpslogger can do with the html-logging setting the same data to the server as this app here.

**Comment by keesj** [comment]
For the sake of completeness I also created a pull request for my version of a python based server in #37

**Comment by keesj** [comment]
ping

**Comment by herverenault** [comment]
@keesj Sorry for being sooo late. Hopefully I can work on this in coming days...

**Comment by herverenault** [comment]
Closing due to lack of time for supporting another language.

**Comment by keesj** [comment]
Hi @herverenault , no problem.
