### ISSUE TITLE
No Data

### ISSUE THREAD

**Issue by wayback3** [herverenault/Self-Hosted-GPS-Tracker#39]
I recognize that this is an unsupported app. I am hoping that someone who has succeeded with this can help me get off the ground.

Tracker executes properly on demo site. Installed scripts on my server and pointed android app to it. App reports location send is successful. i-am-here.html says "Map currently unavailable". I see no data being written to gps-position.txt. perms on server files set to 0777. Any suggestions on where this might be breaking?

**Comment by g3d12** [comment]
The same happens to me?
Did you manage to get it going and writing GPS position to file gps-position.txt?

**Comment by dj2k** [comment]
On my Windows server I changed the path of the gps-position.txt file to "gps-position.txt" (removing the "/tmp" part). So the file is placed right next to gps.php and this is working.
I get the same message "Map currently unavailable", when the i-am-here-position.php is missing. This file is requested by the JavaScript within i-am-here.html. After adding the i-am-here-position.php file to the server, it works. Maybe you have the same issue?
BTW, I have the t= parameter enabled, but this should not make a difference.

**Comment by hippiecool** [comment]
I get the same, app says' Last location sent', but my site says 'Map currently unavailable.'. Demo site (.fr) works as expected. I also do not see the file gps-position.txt being written on my server in /gps (i removed the /tmp from gps.php so it would create it within the same directory as the gps.php file).    Even after I create it and change to 0777 still not writing to it.  Wondering if there is suppose to be a special setting in apache2.conf or 000-default.conf?    Any ideas?

**Comment by Tony-il-Capo** [comment]
Something must be wrong with your server or the link you put on the app.I would bet it's the server part. Probably PHP or Apache not running/configured properly.

I'm not using this app anymore, but I've tested it and it worked like it should. I have tested it on a Raspberry Pi 3b and OpenWrt router, both running Apache. Currently, I only use the server on router, that way I don't need more devices (PC, RPi) running and consuming energy.

Try  GPSLogger (it's here on Github), it has many more features, one of them is sending GPS data (coordinates,..) to your own server. It also sends much more accurate coordinates as it waits for the defined accuracy (value you put on settings). Self-Hosted-GPS-Tracker sends the very first coordinates it gets, so, it's very inaccurate.

You can use the server part from here to start, you may need to change some variables ($_GET) to match them to the ones GPSLogger sends.

It's very important to make sure your server is working properly,  check php, etc...
