### ISSUE TITLE
Adding gps speed

### ISSUE THREAD

**Issue by andikasulis** [herverenault/Self-Hosted-GPS-Tracker#5]
Hello how how to add current gps speed?

thanks
andika sulis

**Comment by jasonhejna** [comment]
Don't believe that is available in the App. Though you could always calculate the distance between a GPS coordinate from the user n minutes ago with one now. Since you know the time difference, you can calculate speed (distance/elapsed time).

**Comment by herverenault** [comment]
Jason Hejna is right : it's not in the app, but you can compute an approximate speed between two points.
