### ISSUE TITLE
Add unique(ish) id to url parameters

### ISSUE THREAD

**Issue by brentfraser** [herverenault/Self-Hosted-GPS-Tracker#6]
I've got two phones so it would be nice if the app would post a ID parameter.  
Something like:
     ...php?ID=MyPhone&lat=....

so I can keep the locations of more than one device.

Thanks!
Brent

**Comment by jasonhejna** [comment]
You can totally do this! Add as many extra query string parameters at you wish.

**Comment by herverenault** [comment]
Jason is right.
Best regards.

**Comment by brentfraser** [comment]
Hey it works!  Thanks
