### ISSUE TITLE
I'd love to find this on F-Droid

### ISSUE THREAD

**Issue by plberd** [herverenault/Self-Hosted-GPS-Tracker#7]
Would it be possible to add it there?

I would send it to the submission queue myself, but it wouldn't be fair. You'd probably want to add your own id and donations address.

But since I don't use google play things I'd really appreciate if it were there.

Thank you

**Comment by herverenault** [comment]
OK, I'll do it.

**Comment by mwgg** [comment]
Agreed, gotta have this on F-Droid.

**Comment by herverenault** [comment]
Ouch, time flies! Eventually, I did it: [https://f-droid.org/forums/topic/self-hosted-gps-tracker/](https://f-droid.org/forums/topic/self-hosted-gps-tracker/)
