### ISSUE TITLE
Allow for unlimited run time

### ISSUE THREAD

**Issue by muesli** [herverenault/Self-Hosted-GPS-Tracker#8]
I'd like to keep this running non-stop, but there seems to be no way to not set a max-run-time.

**Comment by herverenault** [comment]
Max run-time is an Integer, ie. 2^31 - 1 hours == 245146 years. Should be enough ;-)

**Comment by muesli** [comment]
That's not exactly user friendly tho, is it? Why not just allow for setting the value to 0 (in turn disabling the max run time)?

**Comment by herverenault** [comment]
I agree, but right now I have no time for patching it :-(
Pull requests are welcome, though.
