### ISSUE TITLE
how to addsome username to check other user location ?

### ISSUE THREAD

**Issue by muafakul** [herverenault/Self-Hosted-GPS-Tracker#9]
I wish i can see all users location

**Comment by struthio** [comment]
Just simply add value as URL parameter go logging string, ex.

http://my.gloruius.server/gps.php?user=tom
(but If you are going to log many users, then it is better to use some database, not a flat file)

Or you might create separate PHP files for every user ex.

http://my.gloruius.server/gps_tom.php
http://my.gloruius.server/gps_mary.php
etc.

**Comment by herverenault** [comment]
That's correct, struthio.

**Comment by muafakul** [comment]
Huft.but u want all username at one map
